version: "3.5"

services:

  db:
    image: ${MYSQL_IMAGE}
    restart: always
    hostname: ${MYSQL_HOST}
    container_name: ${MYSQL_HOST}
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DB_NAME}
    networks:
      - private
    ports:
      - 3006:3006

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
    - private

  backend:
    build:
      context: ./api
      target: development
    container_name: api
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/api/src
      - ./api/package.json:/api/package.json
      - ./api/package-lock.json:/api/package-lock.json
    env_file: .env
    networks:
      - public
      - private
  app:
    build:
      context: ./app
      args:
        - NODE_ENV=development
    container_name: app
    tty: true
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    volumes:
      - ./app:/app/:delegated
      - ./app/package.json:/app/package.json
      - ./app/package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    env_file: app.env
    healthcheck:
      disable: true
    networks:
      - public
networks:
  public:
  private:
volumes:
  notused:
